name: Hello universe
on : # Whetn will it trigger
  push: #On push it will trigger
    branches: # Whicj branch will it trigger
      - main # On Main branch it will trigger
  workflow_dispatch:
jobs: #Works to be done 
  build_and_test: 
    runs-on: ubuntu-20.04
    steps:
    - name: Clone Code
      uses: action/checkout@v2
    - name: Compile Java File
      shell: bash
      run: javac Main.java
      shell: bash # What shell to use
      run: java Main.java # What it does
    - name: Rund the java file # name of steps
      shell: bash # What shell.to use
      run: java Main.java # what it does